Do a partial style check for pull requests

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -57,8 +57,14 @@ script:
   - cd ../..
   - mkdir -p build
   - cd build
-  - cmake -DRUN_CLANG_TIDY_PY=/usr/bin/run-clang-tidy-6.0.py ..
+  - cmake -DRUN_CLANG_TIDY_PY=/usr/bin/run-clang-tidy-6.0.py -DCHECKS_SOURCE_BRANCH=${TRAVIS_BRANCH} ..
   - make -j2
+  - |
+    if [[ $TRAVIS_TEST_RESULT != 0 ]]; then
+      echo "Compilation failed"
+      cat stylecheck.out
+      exit 1;
+    fi
   - ./unittest/lcunittest
   - make stylecheck > stylecheck.out
   - |
